# -*- coding: utf-8 -*-
"""Counting

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qwHzjMOwFFkJu6ZQmYLyeOEBGjgQzSKw
"""

score=input().split()
count=0
for i in score:
  if int(i)<60:
    count=count+1
print(count)